Repository ice-cream-the-fat-cat/my-niwa-backend, pull requests merged in 2021-09, with the labels that each got.

#40 For after MVP: Add update rule by id
  controllers/v1/rules/rules_controllers.go
  main.go
  models/v1/completed_tasks/completed_tasks_models.go
  models/v1/rules/rules_models.go
  routes/v1/rules/rules_routes.go
Labels: Priority: MEDIUM 👾, review wanted

#61 Feature update garden by gardenId
  controllers/v1/gardens/gardens_controller.go
  main.go
  models/v1/errors/errors_models.go
  models/v1/gardens/gardens_models.go
  routes/v1/gardens/gardens_router.go
  routes/v1/rules/rules_routes.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#63 Feature delete garden by gardenId
  controllers/v1/gardens/gardens_controller.go
  controllers/v1/rules/rules_controllers.go
  main.go
  models/v1/utils/utils.go
  routes/v1/gardens/gardens_router.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#65 Feature Get Flower List
  controllers/v1/flowers/gardens_controller.go
  main.go
  models/v1/flowers/flowers_models.go
  routes/v1/flowers/flowers_router.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#72 Feature test backend performance
  controllers/v1/gardens/gardens_controller.go
  controllers/v1/rules/rules_controllers.go
  routes/v1/gardens/gardens_router.go
  routes/v1/rules/rules_routes.go
  utils/utils.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#73 Develop to staging performance test
  controllers/v1/flowers/gardens_controller.go
  controllers/v1/gardens/gardens_controller.go
  controllers/v1/rules/rules_controllers.go
  main.go
  models/v1/completed_tasks/completed_tasks_models.go
  models/v1/errors/errors_models.go
  models/v1/flowers/flowers_models.go
  models/v1/gardens/gardens_models.go
  models/v1/rules/rules_models.go
  models/v1/utils/utils.go
  routes/v1/flowers/flowers_router.go
  routes/v1/gardens/gardens_router.go
  routes/v1/rules/rules_routes.go
  utils/utils.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#77 Add delete completedTask by completedTaskId
  controllers/v1/completed_tasks/completed_tasks_controllers.go
  main.go
  routes/v1/completed_tasks/completed_tasks.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#78 Feature fix context timeout
  controllers/v1/completed_tasks/completed_tasks_controllers.go
  controllers/v1/flowers/gardens_controller.go
  controllers/v1/gardens/gardens_controller.go
  controllers/v1/rules/rules_controllers.go
  database/mongo_connection.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#80 Code Freeze for Sprint 2 (Develop to staging)
  controllers/v1/completed_tasks/completed_tasks_controllers.go
  controllers/v1/flowers/gardens_controller.go
  controllers/v1/gardens/gardens_controller.go
  controllers/v1/rules/rules_controllers.go
  database/mongo_connection.go
  main.go
  routes/v1/completed_tasks/completed_tasks.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#79 Feature fix fire base user (Can be pushed after Saturday's demo)
  controllers/v1/gardens/gardens_controller.go
  docs/API_document.md
  main.go
  models/v1/gardens/gardens_models.go
  routes/v1/gardens/gardens_router.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#87 Develop to staging breaking change
  controllers/v1/gardens/gardens_controller.go
  docs/API_document.md
  main.go
  models/v1/gardens/gardens_models.go
  routes/v1/gardens/gardens_router.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#76 Added docker for the backend
  .gitignore
  Dockerfile
  docs/how_to_start_developing_the_backend.md
  main.go
Labels: Priority: MEDIUM 👾, review wanted

#71 Create GetUserAccount endpoint with CreateUserAccount function(Want to push #79)
  controllers/v1/users/users_controller.go
  main.go
  models/v1/users/users_models.go
  routes/v1/users/users_router.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#90 Feature add coin after completed task
  controllers/v1/flowers/flowers_controller.go
  controllers/v1/users/users_controller.go
  models/v1/users/users_models.go
  routes/v1/completed_tasks/completed_tasks.go
  routes/v1/users/users_router.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#91 Feature subtract coin after completed task
  main.go
  routes/v1/completed_tasks/completed_tasks.go
  routes/v1/gardens/gardens_router.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#92 Add BuyNewFlower endpoint
  controllers/v1/flowersStore/flowersStore_controller.go
  main.go
  models/v1/flowersStore/flowersStore_models.go
  routes/v1/flowersStore/flowersStore_router.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#95 Add cloudbuild.yaml file for gcp's cloud build
  cloudbuild.yaml
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#96 Develop to staging for GCP
  .gitignore
  Dockerfile
  cloudbuild.yaml
  controllers/v1/flowers/flowers_controller.go
  controllers/v1/flowersStore/flowersStore_controller.go
  controllers/v1/users/users_controller.go
  docs/how_to_start_developing_the_backend.md
  main.go
  models/v1/flowersStore/flowersStore_models.go
  models/v1/users/users_models.go
  routes/v1/completed_tasks/completed_tasks.go
  routes/v1/flowersStore/flowersStore_router.go
  routes/v1/gardens/gardens_router.go
  routes/v1/users/users_router.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#93 Add model, route, and controller for gardenCategories
  controllers/v1/garden_categories/garden_categories_controllers.go
  controllers/v1/gardens/gardens_controller.go
  main.go
  models/v1/garden_categories/garden_categories_models.go
  models/v1/gardens/gardens_models.go
  routes/v1/garden_categories/garden_categories_router.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#97 add logic for check insufficient balance
  controllers/v1/flowersStore/flowersStore_controller.go
  controllers/v1/users/users_controller.go
  models/v1/users/users_models.go
  routes/v1/completed_tasks/completed_tasks.go
  routes/v1/users/users_router.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#99 Create route to handle date
  controllers/v1/completed_tasks/completed_tasks_controllers.go
  controllers/v1/gardens/gardens_controller.go
  main.go
  routes/v1/completed_tasks/completed_tasks.go
  routes/v1/gardens/gardens_router.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#104 Feature prevent spamming of completed task
  controllers/v1/completed_tasks/completed_tasks_controllers.go
  controllers/v1/gardens/gardens_controller.go
  routes/v1/completed_tasks/completed_tasks.go
  utils/utils.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#105 Develop to staging midweek update
  controllers/v1/completed_tasks/completed_tasks_controllers.go
  controllers/v1/flowersStore/flowersStore_controller.go
  controllers/v1/garden_categories/garden_categories_controllers.go
  controllers/v1/gardens/gardens_controller.go
  controllers/v1/users/users_controller.go
  main.go
  models/v1/garden_categories/garden_categories_models.go
  models/v1/gardens/gardens_models.go
  models/v1/users/users_models.go
  routes/v1/completed_tasks/completed_tasks.go
  routes/v1/garden_categories/garden_categories_router.go
  routes/v1/gardens/gardens_router.go
  routes/v1/users/users_router.go
  utils/utils.go
Labels: Priority: HIGH 🏃‍♂️💨

#110 fix put endpoints for API
  main.go
  routes/v1/flowersStore/flowersStore_router.go
  routes/v1/gardens/gardens_router.go
  routes/v1/rules/rules_routes.go
  utils/utils.go
Labels: review wanted

#107 Add endpoint to grab completedTasks for certain date span based on gardenId
  controllers/v1/completed_tasks/completed_tasks_controllers.go
  controllers/v1/gardens/gardens_controller.go
  main.go
  routes/v1/gardens/gardens_router.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#106 Fix return type for completedTask endpoints
  routes/v1/completed_tasks/completed_tasks.go
  utils/utils.go
Labels: bug, Priority: HIGH 🏃‍♂️💨, review wanted

#117 Develop to staging end of week 3
  controllers/v1/completed_tasks/completed_tasks_controllers.go
  controllers/v1/gardens/gardens_controller.go
  main.go
  routes/v1/completed_tasks/completed_tasks.go
  routes/v1/flowersStore/flowersStore_router.go
  routes/v1/gardens/gardens_router.go
  routes/v1/rules/rules_routes.go
  utils/utils.go
Labels: Priority: HIGH 🏃‍♂️💨

#115 Feature populate garden category on garden
  controllers/v1/garden_categories/garden_categories_controllers.go
  controllers/v1/gardens/gardens_controller.go
  models/v1/flowers/flowers_models.go
  models/v1/garden_categories/garden_categories_models.go
  models/v1/gardens/gardens_models.go
  routes/v1/gardens/gardens_router.go
  routes/v1/users/users_router.go
  utils/utils.go
Labels: Priority: HIGH 🏃‍♂️💨

#116 Feature update error handling
  controllers/v1/flowers/flowers_controller.go
  routes/v1/completed_tasks/completed_tasks.go
  routes/v1/flowers/flowers_router.go
  routes/v1/flowersStore/flowersStore_router.go
  routes/v1/garden_categories/garden_categories_router.go
  routes/v1/gardens/gardens_router.go
  routes/v1/rules/rules_routes.go
  routes/v1/users/users_router.go
  utils/utils.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#118 Update create completedTask response to include userData and completedTask
  controllers/v1/garden_categories/garden_categories_controllers.go
  models/v1/users/users_models.go
  routes/v1/completed_tasks/completed_tasks.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#119 Develop to staging fix completed task
  controllers/v1/flowers/flowers_controller.go
  controllers/v1/garden_categories/garden_categories_controllers.go
  controllers/v1/gardens/gardens_controller.go
  models/v1/flowers/flowers_models.go
  models/v1/garden_categories/garden_categories_models.go
  models/v1/gardens/gardens_models.go
  models/v1/users/users_models.go
  routes/v1/completed_tasks/completed_tasks.go
  routes/v1/flowers/flowers_router.go
  routes/v1/flowersStore/flowersStore_router.go
  routes/v1/garden_categories/garden_categories_router.go
  routes/v1/gardens/gardens_router.go
  routes/v1/rules/rules_routes.go
  routes/v1/users/users_router.go
  utils/utils.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#126 Add cloudbuild for staging
  cloudbuild-staging.yaml
Labels: Priority: HIGH 🏃‍♂️💨

#127 Develop to main deployment test
  .gitignore
  Dockerfile
  cloudbuild-staging.yaml
  cloudbuild.yaml
  controllers/v1/completed_tasks/completed_tasks_controllers.go
  controllers/v1/flowers/flowers_controller.go
  controllers/v1/flowersStore/flowersStore_controller.go
  controllers/v1/garden_categories/garden_categories_controllers.go
  controllers/v1/gardens/gardens_controller.go
  controllers/v1/rules/rules_controllers.go
  controllers/v1/users/users_controller.go
  database/mongo_connection.go
  docs/API_document.md
  docs/branches_and_environments.md
  docs/how_to_start_developing_the_backend.md
  go.mod
  go.sum
  main.go
  models/v1/completed_tasks/completed_tasks_models.go
  models/v1/errors/errors_models.go
  models/v1/flowers/flowers_models.go
  models/v1/flowersStore/flowersStore_models.go
  models/v1/garden_categories/garden_categories_models.go
  models/v1/gardens/gardens_models.go
  models/v1/rules/rules_models.go
  models/v1/users/users_models.go
  models/v1/utils/utils.go
  routes/routes.go
  routes/v1/completed_tasks/completed_tasks.go
  routes/v1/flowers/flowers_router.go
  routes/v1/flowersStore/flowersStore_router.go
  routes/v1/garden_categories/garden_categories_router.go
  routes/v1/gardens/gardens_router.go
  routes/v1/routes.go
  routes/v1/rules/rules_routes.go
  routes/v1/users/users_router.go
  utils/utils.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#122 Post validation (Will merge after demo)
  models/v1/completed_tasks/completed_tasks_models.go
  models/v1/gardens/gardens_models.go
  models/v1/rules/rules_models.go
  routes/v1/completed_tasks/completed_tasks.go
  routes/v1/gardens/gardens_router.go
  routes/v1/rules/rules_routes.go
Labels: Priority: MEDIUM 👾, review wanted

#128 Feature add put validation
  controllers/v1/flowersStore/flowersStore_controller.go
  models/v1/flowersStore/flowersStore_models.go
  models/v1/gardens/gardens_models.go
  routes/v1/flowersStore/flowersStore_router.go
  routes/v1/gardens/gardens_router.go
  routes/v1/rules/rules_routes.go
Labels: Priority: MEDIUM 👾, review wanted

#129 Feature add test for create garden
  .gitignore
  main.go
  main_test.go
  utils/utils.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted

#130 Develop to staging for final sprint
  .gitignore
  controllers/v1/flowersStore/flowersStore_controller.go
  main.go
  main_test.go
  models/v1/completed_tasks/completed_tasks_models.go
  models/v1/flowersStore/flowersStore_models.go
  models/v1/gardens/gardens_models.go
  models/v1/rules/rules_models.go
  routes/v1/completed_tasks/completed_tasks.go
  routes/v1/flowersStore/flowersStore_router.go
  routes/v1/gardens/gardens_router.go
  routes/v1/rules/rules_routes.go
  utils/utils.go
Labels: Priority: HIGH 🏃‍♂️💨, review wanted
